### ISSUE TITLE
Merging font-foss to openwebicons

### ISSUE THREAD

**Issue by pierreozoux** [pfefferle/openwebicons#11]
Hey!

I didn't know about your project, so I started: https://github.com/indiehosters/font-foss/

Can you tell me how can I merge it to your project?

Thanks a lot, and good luck with this awesome\* project :)

**Comment by pierreozoux** [comment]
For reference it is still missing `gitlab`, `mediagoblin`, `piwik` and `ghost`.
No stress, I just put it there for future reference! Thanks again for your work :)

**Comment by pierreozoux** [comment]
Can I help you on that? Do you have documentation on how to contribute?

**Comment by pfefferle** [comment]
Oh sorry, we are preparing our move to a new city atm.

There is sadly no good way to contribute yet, sorry.

I think I could add `gitlab` and `ghost` very shortly, but Piwik and mediagoblin seeming a bit tacky because they are only "text". Piwik is kind of OK, because it is short, but I don't think it is a good idea to add mediagoblin as an icon.
